# Generated by Django 4.1.3 on 2022-12-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadouri_de_poveste', '0002_alter_cadou_pret'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadou',
            name='poster',
            field=models.CharField(default=None, max_length=30000, null=True),
        ),
    ]
