# Generated by Django 4.1.3 on 2022-12-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadouri_de_poveste', '0003_cadou_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadou',
            name='pret',
            field=models.FloatField(),
        ),
    ]
